# Generated by Django 6.0.5 on 2026-05-23 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('html_url', models.URLField(max_length=500)),
                ('is_private', models.BooleanField(default=False)),
                ('stargazers_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('open_issues_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
