# Generated by Django 6.0.5 on 2026-05-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_repository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='html_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
